version: '3'

services:
  ops-web:
    environment:
      AUTO_SYNC: 'false'
      AZ_CLIENT_ID: [required]
      AZ_CLIENT_SECRET: [required]
      AZ_TENANT_ID: [required]
      AZ_WORKSHOP_SUBSCRIPTION_ID: ''
      BOOTSTRAP_ADMIN: email@example.com
      CLOUDS_TO_SYNC: aws az
      DEBUG_LAYOUT: 'true'
      # FEATURE_FLAGS: security-groups op-debrief zendesk-widget
      LOG_LEVEL: DEBUG
      OAUTHLIB_INSECURE_TRANSPORT: 1
      POWER_CONTROL_DOMAIN: example.com
      RESET_DATABASE: 'false'
      SECRET_KEY: [required]
      SERVER_NAME: localhost:8080
      SUPPORT_EMAIL: email@example.com
    volumes:
      - D:/projects/ops-web:/ops-web
