version: '3'

services:
  ops-web:
    image: informaticanapresalesops.azurecr.io/ops-web
    build: .
    environment:
      DB: postgres://postgres:postgres@postgres/postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:11.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
