version: '3.8'

services:
  ops-web:
    image: ghcr.io/informatica-na-presales-ops/ops-web
    build: .
    environment:
      DB: postgres://postgres:postgres@postgres/postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:11.9-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
