name: publish-docker-image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag docker.pkg.github.com/informatica-na-presales-ops/ops-web/ops-web:$(date +%s) .
    - run: docker login --password ${DOCKER_PASSWORD} --username ${DOCKER_USERNAME} docker.pkg.github.com
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - run: docker image push docker.pkg.github.com/informatica-na-presales-ops/ops-web/ops-web:$(date +%s)
